#!/bin/bash

# 增强日志测试脚本
echo "=== TURN服务器增强日志测试 ==="
echo "1. 启动TURN服务器..."
echo "2. 服务器将显示详细的客户端追踪信息"
echo "3. 包括认证、分配、权限和数据传输的每个步骤"
echo ""
echo "预期日志格式："
echo "- [时间] === 新客户端会话开始 ==="
echo "- [时间] === 客户端步骤追踪 ==="
echo "- [时间] === TURN 认证请求接收 ==="
echo "- [时间] === TURN 认证成功 ==="
echo "- [时间] === TURN 会话创建 ==="
echo "- [时间] === 权限检查被调用 ==="
echo "- [时间] === 权限自动授予（调试模式）==="
echo "- [时间] === 活跃会话摘要 ==="
echo ""
echo "日志将包含以下关键信息："
echo "- 客户端地址和用户名"
echo "- 会话持续时间和步骤数量"
echo "- 分配、权限和通道的数量"
echo "- 详细的权限检查过程"
echo "- 自动权限授予的原因"
echo ""
echo "如果您看到 'No Permission' 错误，这表示："
echo "1. 客户端跳过了CreatePermission步骤"
echo "2. 但服务器会自动授予权限（调试模式）"
echo "3. 所有步骤都会被详细记录"
echo ""
echo "启动服务器..."
exec ./bin/server 